### ISSUE TITLE
Resulting binary cannot be signed

### ISSUE THREAD

**Issue by kleuter** [fizzyade/makeuniversal#3]
Hi, thanks for the great tool!

One thing, I had to [fix it](https://github.com/fizzyade/makeuniversal/pull/2) in order to skip symlinks for correct handling of Qt frameworks.
Otherwise it replaces symlinks with original files and the binary couldn't be signed resulting:

`bundle format is ambiguous (could be app or framework)`

Now it works faster of cause too 😄

**Comment by fizzyade** [comment]
patch applied and now in master.

Thank you for you work!
